version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - cd NODE_TASK1
      - npm ci

  build:
    commands:
      - echo "Node.js application build completed successfully!"

artifacts:
  base-directory: NODE_TASK1
  files:
    - '**/*'
  exclude-paths:
    - '.env'